[project]
name = "campus-connect"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "certifi>=2026.1.4",
    "dotenv>=0.9.9",
    "fastapi>=0.128.0",
    "flask>=3.1.2",
    "pymongo>=4.16.0",
    "uvicorn>=0.40.0",
]
